### ISSUE TITLE
[Clients] - Faire la table client : 10 minutes

### ISSUE THREAD

**Issue by alexisyanguas** [btssiochalon/nemo#13]

**Comment by alexisyanguas** [comment]
- [ ] [#13] (https://github.com/btssiochalon/nemo/issues/13) - [Clients] - Faire la table client : 10 minutes
- [ ] [#14] (https://github.com/btssiochalon/nemo/issues/14) - [Clients] - Faire la classe clients C# : 15 minutes
- [ ] [#15] (https://github.com/btssiochalon/nemo/issues/15) - [Clients] - Faire les requêtes SQL dans la classe bdd : 45 minutes
- [ ] [#16] (https://github.com/btssiochalon/nemo/issues/16) - [Clients] - Interface graphique Ajout/Modification : 30 minutes
- [ ] [#17] (https://github.com/btssiochalon/nemo/issues/17) - [Clients] - Back de la vue : 2 heures
- [ ] [#18] (https://github.com/btssiochalon/nemo/issues/18) - [Clients] - Tests unitaires de la classe : 1 heures
